[package]
name = "nom-diagnostic"
edition = "2021"
authors = ["Leon Tan"]
version = "0.1.0"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
nom = { version = "7.1.3" }
codespan = { version = "0.11.1" }
# thiserror = { version = "1.0.40" }